/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorDetalle;
import Controlador.DataBaseFactory;
import Modelo.Detalle;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yefguaar
 */
public class GestionDetalles extends javax.swing.JPanel {

    /**
     * Creates new form GestionDetalles
     */
    ControladorDetalle controladorDetalle;
    
    public GestionDetalles(DataBaseFactory f) {
        controladorDetalle = new ControladorDetalle(f.getDataBase());
        initComponents();
        actualizarTabla();
    }
    
    Detalle getDatos() {
        Detalle d = new Detalle();
        d.Tipo = jcbTipoDetalle.getSelectedItem().toString();
        d.Nombre = jtfNombre.getText();
        d.Descripcion = jtfDescripcion.getText();
        return d;
    }
    
    private void setDatos(Detalle d) {
        jcbTipoDetalle.setSelectedItem(d.Tipo);
        jtfNombre.setText(d.Nombre);
        jtfDescripcion.setText(d.Descripcion);
    }
    
    void actualizarTabla() {
        List<Detalle> lstDetalles = controladorDetalle.listarDetalles();
        DefaultTableModel modelo = (DefaultTableModel) jtbDetalle.getModel();
        
        int nroFIlas = modelo.getRowCount();
        for (int i = 0; i < nroFIlas; i++) {
            modelo.removeRow(0);
        }
        
        if (lstDetalles.size() > 0) {
            for (Detalle d : lstDetalles) {
                
                Object[] fila;
                fila = new Object[]{
                    d.Nombre,
                    d.Descripcion,
                    d.Tipo
                };
                modelo.addRow(fila);
            }
        }
        jtbDetalle.setModel(modelo);
    }
    
    void limpiarFormulario() {
        jtfNombre.setText("");
        jtfDescripcion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDetalle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfDescripcion = new javax.swing.JTextField();
        jcbTipoDetalle = new javax.swing.JComboBox();
        jbtLimpiar = new javax.swing.JButton();
        jbtActualizar = new javax.swing.JButton();
        jbtRegistrar = new javax.swing.JButton();

        jtbDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDetalle);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestion Detalle");

        jLabel2.setText("Tipo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Descripcion");

        jcbTipoDetalle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Devengado", "Deduccion" }));

        jbtLimpiar.setText("Limpiar");
        jbtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimpiarActionPerformed(evt);
            }
        });

        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });

        jbtRegistrar.setText("Registrar");
        jbtRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jtfDescripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbTipoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtRegistrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbTipoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtRegistrar)
                    .addComponent(jbtActualizar)
                    .addComponent(jbtLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegistrarActionPerformed
        // TODO add your handling code here:
        if (controladorDetalle.insertarDetalle(getDatos())) {
            JOptionPane.showMessageDialog(this, "Detalle registrado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            limpiarFormulario();
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar Detalle", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtRegistrarActionPerformed

    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        // TODO add your handling code here:
        if (controladorDetalle.actualizarDetalle(getDatos())) {
            JOptionPane.showMessageDialog(this, "Detalle actualizado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar Detalle", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    private void jtbDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDetalleMouseClicked
        // TODO add your handling code here:
        Detalle d = new Detalle();
        d.Nombre = jtbDetalle.getValueAt(jtbDetalle.getSelectedRow(), 0).toString();
        d.Descripcion = jtbDetalle.getValueAt(jtbDetalle.getSelectedRow(), 1).toString();
        d.Tipo = jtbDetalle.getValueAt(jtbDetalle.getSelectedRow(), 2).toString();

        setDatos(d);
    }//GEN-LAST:event_jtbDetalleMouseClicked

    private void jbtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_jbtLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtLimpiar;
    private javax.swing.JButton jbtRegistrar;
    private javax.swing.JComboBox jcbTipoDetalle;
    private javax.swing.JTable jtbDetalle;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
