/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorDetalle;
import Controlador.ControladorDetalleFijo;
import Controlador.ControladorEmpleado;
import Controlador.DataBaseFactory;
import Modelo.Detalle;
import Modelo.DetalleFijo;
import Modelo.Empleado;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yefguaar
 */
public class GestionDetalleFijo extends javax.swing.JPanel {

    /**
     * Creates new form GestionDetalleFijo
     */
    ControladorDetalle controladorDetalle;
    ControladorDetalleFijo controladorDetalleFijo;
    ControladorEmpleado controladorEmpleado;
    List<Empleado> lstEmpleado;
    List<Detalle> lstDetalle;

    public GestionDetalleFijo(DataBaseFactory f) {
        controladorDetalle = new ControladorDetalle(f.getDataBase());
        controladorDetalleFijo = new ControladorDetalleFijo(f.getDataBase());
        controladorEmpleado = new ControladorEmpleado(f.getDataBase());
        initComponents();
        inicializarEmpleados();
        inicializarDetalles();
        actualizarTabla();
    }

    void inicializarEmpleados() {
        lstEmpleado = controladorEmpleado.listarEmpleados();
        for (Empleado e : lstEmpleado) {
            jcbEmpleado.addItem(e.Nombre +" "+ e.Apellido);
        }
    }

    void inicializarDetalles() {
        lstDetalle = controladorDetalle.listarDetalles();
        for (Detalle d : lstDetalle) {
            jcbDetalle.addItem(d.Nombre + " - " + d.Tipo);
        }
    }

    void actualizarTabla() {
        List<DetalleFijo> lstDetallesFijos = controladorDetalleFijo.listarDetallesFijos();
        DefaultTableModel modelo = (DefaultTableModel) jtbDetalleFijo.getModel();

        int nroFIlas = modelo.getRowCount();
        for (int i = 0; i < nroFIlas; i++) {
            modelo.removeRow(0);
        }

        if (lstDetallesFijos.size() > 0) {
            for (DetalleFijo d : lstDetallesFijos) {
                Object[] fila;
                fila = new Object[]{
                    d.Empleado,
                    d.Nombre,
                    d.ValorUnitario
                };
                modelo.addRow(fila);
            }
        }
        jtbDetalleFijo.setModel(modelo);
    }
    
    DetalleFijo getDatos() {
        DetalleFijo d = new DetalleFijo();
        d.Empleado =  lstEmpleado.get(jcbEmpleado.getSelectedIndex()).Identificacion;
        d.Nombre = lstDetalle.get(jcbDetalle.getSelectedIndex()).Nombre;
        d.ValorUnitario = Double.parseDouble(jtfValorUnitario.getText());
        return d;
    }
    
    void limpiarFormulario() {
        jtfValorUnitario.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfValorUnitario = new javax.swing.JTextField();
        jcbEmpleado = new javax.swing.JComboBox();
        jcbDetalle = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDetalleFijo = new javax.swing.JTable();
        jbtRegistrar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestion Detalle Fijo");

        jLabel2.setText("Empleado");

        jLabel3.setText("Detalle");

        jLabel4.setText("Valor Unitario");

        jtbDetalleFijo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Empleado", "Detalle", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbDetalleFijo);

        jbtRegistrar.setText("Registrar");
        jbtRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jcbDetalle, 0, 200, Short.MAX_VALUE)
                                    .addComponent(jcbEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfValorUnitario))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtRegistrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jbtRegistrar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegistrarActionPerformed
        // TODO add your handling code here:
        if (controladorDetalleFijo.insertarDetalleFijo(getDatos())) {
            JOptionPane.showMessageDialog(this, "Detalle Fijo registrado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            limpiarFormulario();
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar Detalle Fijo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtRegistrar;
    private javax.swing.JComboBox jcbDetalle;
    private javax.swing.JComboBox jcbEmpleado;
    private javax.swing.JTable jtbDetalleFijo;
    private javax.swing.JTextField jtfValorUnitario;
    // End of variables declaration//GEN-END:variables
}
